### ISSUE TITLE
Issue with initial get of Theme preference

### ISSUE THREAD

**Issue by davefxy** [microsoft/dotnet-podcasts#150]
I don't know if I am using this app properly. on my PC running Windows 11, I am compiling and running only the Mobile app. When I run the Mobile app it immediately errors out with a null reference because the Theme preference has never been set;
The line in error is in Settings.cs :
     `get => Enum.Parse<AppTheme>(Preferences.Get(nameof(Theme), Enum.GetName(theme)));`
Since the Theme preference has never been set, the code gets a null reference.
To get this app to run, I modified the code as follows:
```
     get {
           if (!Preferences.ContainsKey(nameof(Settings.Theme)))
                Preferences.Default.Set(nameof(Settings.Theme), "Light");
            return Enum.Parse<AppTheme>(Preferences.Get(nameof(Theme), Enum.GetName(theme)));
        }
```
This is done only to demonstrate I determined a possible reason for the error.

**Comment by jamesmontemagno** [comment]
I put in Light so that should fix it up any mroe. let me know.

**Comment by victorperez2911** [comment]
Hi

here the error still occurs if I start the project as "Windows Machine" as Target, but it does not occur if I use the Android target (Emulator)

![image](https://user-images.githubusercontent.com/11770654/187958585-b619bc16-1456-4322-806e-fb869ce9fda2.png)

**Comment by jamesmontemagno** [comment]
Yup, i jsut saw this as well, fixing up
